version: "3"

services:

  sign-exe:
    image: likesistemas/exe-sign:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CERT_PASSWORD=$CERT_PASSWORD
    volumes:
      - ./work/:/work/