name: Sign Executable

on:
  workflow_call:
    inputs:
      executable-path:
        description: 'Path to the executable file to sign'
        required: true
        type: string
      signed-executable-name:
        description: 'Name for the signed executable (optional)'
        required: false
        type: string
        default: 'signed-executable.exe'
      upload-artifact:
        description: 'Upload signed executable as artifact'
        required: false
        type: boolean
        default: true
    secrets:
      CERTIFICATE_PASSWORD:
        required: true
        description: 'Password for the certificate file'
      CERTIFICATE_BASE64:
        required: true
        description: 'Base64 encoded certificate file (.pfx)'
      SIGNING_PASSWORD:
        description: 'Additional signing password (optional)'
        required: false

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create work directory
        run: mkdir -p work

      - name: Copy executable to work directory
        run: |
          cp "${{ inputs.executable-path }}" work/app.exe

      - name: Sign executable
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/work:/work \
            -e CERTIFICATE_BASE64="${{ secrets.CERTIFICATE_BASE64 }}" \
            -e CERTIFICATE_PASSWORD="${{ secrets.CERTIFICATE_PASSWORD }}" \
            -e EXE_FILE="app.exe" \
            -e EXE_SIGNED="${{ inputs.signed-executable-name }}" \
            -e PASSWORD="${{ secrets.SIGNING_PASSWORD || 'like' }}" \
            ricardoapaes/exe-sign:latest

      - name: Upload signed executable
        if: ${{ inputs.upload-artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: signed-executable
          path: work/${{ inputs.signed-executable-name }}
          retention-days: 30

      - name: Copy signed executable back
        if: ${{ !inputs.upload-artifact }}
        run: |
          cp work/${{ inputs.signed-executable-name }} ${{ inputs.executable-path }}.signed